import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline": "#777771",
        "inverse-on-surface": "#f2f1ee",
        "tertiary": "#000000",
        "on-secondary-fixed": "#3b0900",
        "surface-container": "#efeeeb",
        "on-background": "#1a1c1a",
        "tertiary-container": "#1b1c16",
        "surface-tint": "#5f5e5c",
        "on-tertiary-fixed-variant": "#474740",
        "on-tertiary-fixed": "#1b1c16",
        "tertiary-fixed-dim": "#c8c7bd",
        "tertiary-fixed": "#e4e3d9",
        "surface-bright": "#faf9f6",
        "on-primary-fixed": "#1c1c1a",
        "on-surface": "#1a1c1a",
        "on-surface-variant": "#474741",
        "surface": "#faf9f6",
        "surface-dim": "#dbdad7",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#fe9071",
        "primary": "#010100",
        "surface-container-high": "#e9e8e5",
        "on-primary": "#ffffff",
        "outline-variant": "#c8c7bf",
        "error-container": "#ffdad6",
        "surface-variant": "#e3e2e0",
        "secondary-fixed-dim": "#ffb5a0",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#ffdbd1",
        "on-secondary-fixed-variant": "#7c2d15",
        "error": "#ba1a1a",
        "primary-fixed": "#e5e2de",
        "primary-container": "#1c1c1a",
        "surface-container-low": "#f4f3f1",
        "surface-container-highest": "#e3e2e0",
        "primary-fixed-dim": "#c8c6c3",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#85847c",
        "on-primary-fixed-variant": "#474744",
        "inverse-primary": "#c8c6c3",
        "background": "#faf9f6",
        "inverse-surface": "#2f312f",
        "on-secondary-container": "#752811",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "secondary": "#9b442a",
        "on-primary-container": "#858481",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "20px",
        "section-v-padding": "104px",
        "margin-desktop": "80px",
        "section-v-padding-mobile": "64px",
        "gutter": "24px",
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "eyebrow-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "label-md": ["Inter", "sans-serif"],
        "display-xl": ["Playfair Display", "serif"],
        "display-xl-mobile": ["Playfair Display", "serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "eyebrow-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "28px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "0em", fontWeight: "500" }],
        "headline-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        "display-xl": ["84px", { lineHeight: "92px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "display-xl-mobile": ["48px", { lineHeight: "54px", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
